// @generated by tools/generate_exports.py; do not edit.
//! C exports preserving Elide transport ABI 3.
#![allow(clippy::too_many_arguments)]
use bemo::abi::{BufferView, NativeEvent, ReceiveResult};
use std::ffi::c_void;
/// Forward to [`bemo::abi::engine::elide_transport_engine_context_new`].
///
/// # Safety
/// The caller must satisfy the safety contract of [`bemo::abi::engine::elide_transport_engine_context_new`].
#[unsafe(no_mangle)]
pub unsafe extern "C" fn elide_transport_engine_context_new(
  workload: u64,
  flags: u32,
  certificates: *const u8,
  certificates_length: u64,
  key: *const u8,
  key_length: u64,
  alpn: *const u8,
  alpn_length: u64,
) -> u64 {
  // SAFETY: the exported contract is identical to the Rust handle API.
  unsafe {
    bemo::abi::engine::elide_transport_engine_context_new(
      workload,
      flags,
      certificates,
      certificates_length,
      key,
      key_length,
      alpn,
      alpn_length,
    )
  }
}

/// Forward to [`bemo::abi::engine::elide_transport_engine_context_release`].
#[unsafe(no_mangle)]
pub extern "C" fn elide_transport_engine_context_release(context: u64) -> i32 {
  bemo::abi::engine::elide_transport_engine_context_release(context)
}

/// Forward to [`bemo::abi::engine::elide_transport_engine_new`].
///
/// # Safety
/// The caller must satisfy the safety contract of [`bemo::abi::engine::elide_transport_engine_new`].
#[unsafe(no_mangle)]
pub unsafe extern "C" fn elide_transport_engine_new(
  workload: u64,
  context: u64,
  name: *const u8,
  name_length: u64,
) -> u64 {
  // SAFETY: the exported contract is identical to the Rust handle API.
  unsafe { bemo::abi::engine::elide_transport_engine_new(workload, context, name, name_length) }
}

/// Forward to [`bemo::abi::engine::elide_transport_engine_wrap`].
///
/// # Safety
/// The caller must satisfy the safety contract of [`bemo::abi::engine::elide_transport_engine_wrap`].
#[unsafe(no_mangle)]
pub unsafe extern "C" fn elide_transport_engine_wrap(
  engine: u64,
  source: *const u8,
  source_length: u64,
  destination: *mut u8,
  destination_length: u64,
) -> i64 {
  // SAFETY: the exported contract is identical to the Rust handle API.
  unsafe {
    bemo::abi::engine::elide_transport_engine_wrap(engine, source, source_length, destination, destination_length)
  }
}

/// Forward to [`bemo::abi::engine::elide_transport_engine_unwrap`].
///
/// # Safety
/// The caller must satisfy the safety contract of [`bemo::abi::engine::elide_transport_engine_unwrap`].
#[unsafe(no_mangle)]
pub unsafe extern "C" fn elide_transport_engine_unwrap(
  engine: u64,
  source: *mut u8,
  source_length: u64,
  destination: *mut u8,
  destination_length: u64,
  flags: u32,
) -> i64 {
  // SAFETY: the exported contract is identical to the Rust handle API.
  unsafe {
    bemo::abi::engine::elide_transport_engine_unwrap(
      engine,
      source,
      source_length,
      destination,
      destination_length,
      flags,
    )
  }
}

/// Forward to [`bemo::abi::engine::elide_transport_engine_control`].
#[unsafe(no_mangle)]
pub extern "C" fn elide_transport_engine_control(engine: u64, operation: u32) -> i64 {
  bemo::abi::engine::elide_transport_engine_control(engine, operation)
}

/// Forward to [`bemo::abi::engine::elide_transport_engine_info`].
///
/// # Safety
/// The caller must satisfy the safety contract of [`bemo::abi::engine::elide_transport_engine_info`].
#[unsafe(no_mangle)]
pub unsafe extern "C" fn elide_transport_engine_info(
  engine: u64,
  kind: u32,
  index: u32,
  output: *mut u8,
  capacity: u64,
) -> i32 {
  // SAFETY: the exported contract is identical to the Rust handle API.
  unsafe { bemo::abi::engine::elide_transport_engine_info(engine, kind, index, output, capacity) }
}

/// Forward to [`bemo::abi::engine::elide_transport_engine_release`].
#[unsafe(no_mangle)]
pub extern "C" fn elide_transport_engine_release(engine: u64) -> i32 {
  bemo::abi::engine::elide_transport_engine_release(engine)
}

/// Forward to [`bemo::abi::elide_transport_gzip_new`].
#[unsafe(no_mangle)]
pub extern "C" fn elide_transport_gzip_new(workload: u64, level: u32) -> u64 {
  bemo::abi::elide_transport_gzip_new(workload, level)
}

/// Forward to [`bemo::abi::elide_transport_gzip_compress`].
#[unsafe(no_mangle)]
pub extern "C" fn elide_transport_gzip_compress(workload: u64, encoder: u64, input: u64) -> u64 {
  bemo::abi::elide_transport_gzip_compress(workload, encoder, input)
}

/// Forward to [`bemo::abi::elide_transport_gzip_release`].
#[unsafe(no_mangle)]
pub extern "C" fn elide_transport_gzip_release(encoder: u64) -> i32 {
  bemo::abi::elide_transport_gzip_release(encoder)
}

/// Forward to [`bemo::abi::elide_transport_socket_http`].
#[unsafe(no_mangle)]
pub extern "C" fn elide_transport_socket_http(
  workload: u64,
  driver: u64,
  socket: u64,
  owner: u64,
  capacity: u64,
) -> i32 {
  bemo::abi::elide_transport_socket_http(workload, driver, socket, owner, capacity)
}

/// Forward to [`bemo::abi::elide_transport_socket_http_tls`].
#[unsafe(no_mangle)]
pub extern "C" fn elide_transport_socket_http_tls(
  workload: u64,
  driver: u64,
  socket: u64,
  owner: u64,
  capacity: u64,
  context: u64,
) -> i32 {
  bemo::abi::elide_transport_socket_http_tls(workload, driver, socket, owner, capacity, context)
}

/// Forward to [`bemo::abi::elide_transport_http_drain`].
#[unsafe(no_mangle)]
pub extern "C" fn elide_transport_http_drain(driver: u64) -> i32 {
  bemo::abi::elide_transport_http_drain(driver)
}

/// Forward to [`bemo::abi::elide_transport_http_retire`].
#[unsafe(no_mangle)]
pub extern "C" fn elide_transport_http_retire(driver: u64) -> i32 {
  bemo::abi::elide_transport_http_retire(driver)
}

/// Forward to [`bemo::abi::elide_transport_http_segment_release_retired`].
#[unsafe(no_mangle)]
pub extern "C" fn elide_transport_http_segment_release_retired(segment: u64) -> i32 {
  bemo::abi::elide_transport_http_segment_release_retired(segment)
}

/// Forward to [`bemo::abi::elide_transport_http_method`].
#[unsafe(no_mangle)]
pub extern "C" fn elide_transport_http_method(exchange: u64) -> i32 {
  bemo::abi::elide_transport_http_method(exchange)
}

/// Forward to [`bemo::abi::elide_transport_http_version`].
#[unsafe(no_mangle)]
pub extern "C" fn elide_transport_http_version(exchange: u64) -> i32 {
  bemo::abi::elide_transport_http_version(exchange)
}

/// Forward to [`bemo::abi::elide_transport_http_header_count`].
#[unsafe(no_mangle)]
pub extern "C" fn elide_transport_http_header_count(exchange: u64) -> i32 {
  bemo::abi::elide_transport_http_header_count(exchange)
}

/// Forward to [`bemo::abi::elide_transport_http_keep_alive`].
#[unsafe(no_mangle)]
pub extern "C" fn elide_transport_http_keep_alive(exchange: u64) -> i32 {
  bemo::abi::elide_transport_http_keep_alive(exchange)
}

/// Forward to [`bemo::abi::elide_transport_http_view`].
///
/// # Safety
/// The caller must satisfy the safety contract of [`bemo::abi::elide_transport_http_view`].
#[unsafe(no_mangle)]
pub unsafe extern "C" fn elide_transport_http_view(exchange: u64, kind: u32, index: u32, output: *mut u64) -> i32 {
  // SAFETY: the exported contract is identical to the Rust handle API.
  unsafe { bemo::abi::elide_transport_http_view(exchange, kind, index, output) }
}

/// Forward to [`bemo::abi::elide_transport_http_spans`].
///
/// # Safety
/// The caller must satisfy the safety contract of [`bemo::abi::elide_transport_http_spans`].
#[unsafe(no_mangle)]
pub unsafe extern "C" fn elide_transport_http_spans(exchange: u64, output: *mut u32, capacity: u32) -> i32 {
  // SAFETY: the exported contract is identical to the Rust handle API.
  unsafe { bemo::abi::elide_transport_http_spans(exchange, output, capacity) }
}

/// Forward to [`bemo::abi::elide_transport_http_respond`].
///
/// # Safety
/// The caller must satisfy the safety contract of [`bemo::abi::elide_transport_http_respond`].
#[unsafe(no_mangle)]
pub unsafe extern "C" fn elide_transport_http_respond(
  driver: u64,
  exchange: u64,
  status: u32,
  headers: *const u64,
  count: u32,
  body: *const u8,
  body_length: u64,
  flags: u32,
) -> i32 {
  // SAFETY: the exported contract is identical to the Rust handle API.
  unsafe { bemo::abi::elide_transport_http_respond(driver, exchange, status, headers, count, body, body_length, flags) }
}

/// Forward to [`bemo::abi::elide_transport_http_chunk_prepare`].
///
/// # Safety
/// The caller must satisfy the safety contract of [`bemo::abi::elide_transport_http_chunk_prepare`].
#[unsafe(no_mangle)]
pub unsafe extern "C" fn elide_transport_http_chunk_prepare(exchange: u64, capacity: u64, address: *mut u64) -> u64 {
  // SAFETY: the exported contract is identical to the Rust handle API.
  unsafe { bemo::abi::elide_transport_http_chunk_prepare(exchange, capacity, address) }
}

/// Forward to [`bemo::abi::elide_transport_http_chunk_send`].
#[unsafe(no_mangle)]
pub extern "C" fn elide_transport_http_chunk_send(
  driver: u64,
  exchange: u64,
  buffer: u64,
  length: u64,
  flags: u32,
) -> i32 {
  bemo::abi::elide_transport_http_chunk_send(driver, exchange, buffer, length, flags)
}

/// Forward to [`bemo::abi::elide_transport_http_head_release`].
///
/// # Safety
/// The caller must satisfy the safety contract of [`bemo::abi::elide_transport_http_head_release`].
#[unsafe(no_mangle)]
pub unsafe extern "C" fn elide_transport_http_head_release(head: u64) -> i32 {
  // SAFETY: the exported contract is identical to the Rust handle API.
  unsafe { bemo::abi::elide_transport_http_head_release(head) }
}

/// Forward to [`bemo::abi::elide_transport_http_prepare`].
///
/// # Safety
/// The caller must satisfy the safety contract of [`bemo::abi::elide_transport_http_prepare`].
#[unsafe(no_mangle)]
pub unsafe extern "C" fn elide_transport_http_prepare(exchange: u64, capacity: u64) -> u64 {
  // SAFETY: the exported contract is identical to the Rust handle API.
  unsafe { bemo::abi::elide_transport_http_prepare(exchange, capacity) }
}

/// Forward to [`bemo::abi::elide_transport_http_send`].
#[unsafe(no_mangle)]
pub extern "C" fn elide_transport_http_send(driver: u64, exchange: u64, length: u64, flags: u32) -> i32 {
  bemo::abi::elide_transport_http_send(driver, exchange, length, flags)
}

/// Forward to [`bemo::abi::elide_transport_http_release`].
#[unsafe(no_mangle)]
pub extern "C" fn elide_transport_http_release(driver: u64, exchange: u64) -> i32 {
  bemo::abi::elide_transport_http_release(driver, exchange)
}

/// Forward to [`bemo::abi::elide_transport_http_free`].
#[unsafe(no_mangle)]
pub extern "C" fn elide_transport_http_free(driver: u64, exchange: u64) -> i32 {
  bemo::abi::elide_transport_http_free(driver, exchange)
}

/// Forward to [`bemo::abi::elide_transport_http_segment_ack`].
#[unsafe(no_mangle)]
pub extern "C" fn elide_transport_http_segment_ack(driver: u64, segment: u64) -> i32 {
  bemo::abi::elide_transport_http_segment_ack(driver, segment)
}

/// Forward to [`bemo::abi::elide_transport_http_segment_release`].
#[unsafe(no_mangle)]
pub extern "C" fn elide_transport_http_segment_release(driver: u64, segment: u64) -> i32 {
  bemo::abi::elide_transport_http_segment_release(driver, segment)
}

/// Forward to [`bemo::abi::elide_transport_http_retain`].
///
/// # Safety
/// The caller must satisfy the safety contract of [`bemo::abi::elide_transport_http_retain`].
#[unsafe(no_mangle)]
pub unsafe extern "C" fn elide_transport_http_retain(exchange: u64, length: *mut u64) -> u64 {
  // SAFETY: the exported contract is identical to the Rust handle API.
  unsafe { bemo::abi::elide_transport_http_retain(exchange, length) }
}

/// Forward to [`bemo::abi::elide_transport_serving_available_cores`].
#[unsafe(no_mangle)]
pub extern "C" fn elide_transport_serving_available_cores() -> i32 {
  bemo::abi::elide_transport_serving_available_cores()
}

/// Forward to [`bemo::abi::elide_transport_serving_context_enter`].
#[unsafe(no_mangle)]
pub extern "C" fn elide_transport_serving_context_enter(application: u64, replica: u32) -> i32 {
  bemo::abi::elide_transport_serving_context_enter(application, replica)
}

/// Forward to [`bemo::abi::elide_transport_serving_context_leave`].
#[unsafe(no_mangle)]
pub extern "C" fn elide_transport_serving_context_leave() -> i32 {
  bemo::abi::elide_transport_serving_context_leave()
}

/// Forward to [`bemo::abi::elide_transport_serving_helper_prepare`].
#[unsafe(no_mangle)]
pub extern "C" fn elide_transport_serving_helper_prepare() -> u64 {
  bemo::abi::elide_transport_serving_helper_prepare()
}

/// Forward to [`bemo::abi::elide_transport_serving_helper_release`].
///
/// # Safety
/// The caller must satisfy the safety contract of [`bemo::abi::elide_transport_serving_helper_release`].
#[unsafe(no_mangle)]
pub unsafe extern "C" fn elide_transport_serving_helper_release(token: u64) -> i32 {
  // SAFETY: the exported contract is identical to the Rust handle API.
  unsafe { bemo::abi::elide_transport_serving_helper_release(token) }
}

/// Forward to [`bemo::abi::elide_transport_serving_helper_start`].
///
/// # Safety
/// The caller must satisfy the safety contract of [`bemo::abi::elide_transport_serving_helper_start`].
#[unsafe(no_mangle)]
pub unsafe extern "C" fn elide_transport_serving_helper_start(token: u64) -> i32 {
  // SAFETY: the exported contract is identical to the Rust handle API.
  unsafe { bemo::abi::elide_transport_serving_helper_start(token) }
}

/// Forward to [`bemo::abi::elide_transport_serving_new`].
#[unsafe(no_mangle)]
pub extern "C" fn elide_transport_serving_new(count: u32) -> u64 {
  bemo::abi::elide_transport_serving_new(count)
}

/// Forward to [`bemo::abi::elide_transport_serving_split_new`].
#[unsafe(no_mangle)]
pub extern "C" fn elide_transport_serving_split_new(count: u32) -> u64 {
  bemo::abi::elide_transport_serving_split_new(count)
}

/// Forward to [`bemo::abi::elide_transport_serving_workers`].
#[unsafe(no_mangle)]
pub extern "C" fn elide_transport_serving_workers(application: u64, context: u32) -> i32 {
  bemo::abi::elide_transport_serving_workers(application, context)
}

/// Forward to [`bemo::abi::elide_transport_serving_worker_driver`].
#[unsafe(no_mangle)]
pub extern "C" fn elide_transport_serving_worker_driver(
  workload: u64,
  application: u64,
  context: u32,
  worker: u32,
  backend: u32,
  limit: u32,
) -> u64 {
  bemo::abi::elide_transport_serving_worker_driver(workload, application, context, worker, backend, limit)
}

/// Forward to [`bemo::abi::elide_transport_serving_driver`].
#[unsafe(no_mangle)]
pub extern "C" fn elide_transport_serving_driver(
  workload: u64,
  application: u64,
  index: u32,
  backend: u32,
  limit: u32,
  affinity: u32,
) -> u64 {
  bemo::abi::elide_transport_serving_driver(workload, application, index, backend, limit, affinity)
}

/// Forward to [`bemo::abi::elide_transport_serving_listen`].
#[unsafe(no_mangle)]
pub extern "C" fn elide_transport_serving_listen(
  workload: u64,
  driver: u64,
  endpoint: u64,
  signature: u64,
  backlog: i32,
) -> u64 {
  bemo::abi::elide_transport_serving_listen(workload, driver, endpoint, signature, backlog)
}

/// Forward to [`bemo::abi::elide_transport_serving_ready`].
#[unsafe(no_mangle)]
pub extern "C" fn elide_transport_serving_ready(driver: u64) -> i32 {
  bemo::abi::elide_transport_serving_ready(driver)
}

/// Forward to [`bemo::abi::elide_transport_serving_cpu`].
#[unsafe(no_mangle)]
pub extern "C" fn elide_transport_serving_cpu(driver: u64) -> i32 {
  bemo::abi::elide_transport_serving_cpu(driver)
}

/// Forward to [`bemo::abi::elide_transport_serving_listener_close`].
#[unsafe(no_mangle)]
pub extern "C" fn elide_transport_serving_listener_close(driver: u64, listener: u64) -> i32 {
  bemo::abi::elide_transport_serving_listener_close(driver, listener)
}

/// Forward to [`bemo::abi::elide_transport_serving_close`].
#[unsafe(no_mangle)]
pub extern "C" fn elide_transport_serving_close(application: u64) -> i32 {
  bemo::abi::elide_transport_serving_close(application)
}

/// Forward to [`bemo::abi::elide_transport_last_error`].
#[unsafe(no_mangle)]
pub extern "C" fn elide_transport_last_error() -> i32 {
  bemo::abi::elide_transport_last_error()
}

/// Forward to [`bemo::abi::elide_transport_socket_listen`].
#[unsafe(no_mangle)]
pub extern "C" fn elide_transport_socket_listen(
  workload: u64,
  driver: u64,
  endpoint: u64,
  backlog: i32,
  reuse: u32,
) -> u64 {
  bemo::abi::elide_transport_socket_listen(workload, driver, endpoint, backlog, reuse)
}

/// Forward to [`bemo::abi::elide_transport_socket_connect`].
#[unsafe(no_mangle)]
pub extern "C" fn elide_transport_socket_connect(workload: u64, driver: u64, endpoint: u64) -> u64 {
  bemo::abi::elide_transport_socket_connect(workload, driver, endpoint)
}

/// Forward to [`bemo::abi::elide_transport_socket_accept`].
#[unsafe(no_mangle)]
pub extern "C" fn elide_transport_socket_accept(workload: u64, driver: u64, listener: u64) -> u64 {
  bemo::abi::elide_transport_socket_accept(workload, driver, listener)
}

/// Forward to [`bemo::abi::elide_transport_socket_adopt`].
#[unsafe(no_mangle)]
pub extern "C" fn elide_transport_socket_adopt(workload: u64, driver: u64, accepted: u64) -> i32 {
  bemo::abi::elide_transport_socket_adopt(workload, driver, accepted)
}

/// Forward to [`bemo::abi::elide_transport_socket_discard`].
#[unsafe(no_mangle)]
pub extern "C" fn elide_transport_socket_discard(accepted: u64) -> i32 {
  bemo::abi::elide_transport_socket_discard(accepted)
}

/// Forward to [`bemo::abi::elide_transport_socket_address`].
#[unsafe(no_mangle)]
pub extern "C" fn elide_transport_socket_address(driver: u64, socket: u64, peer: u32, output: u64) -> i32 {
  bemo::abi::elide_transport_socket_address(driver, socket, peer, output)
}

/// Forward to [`bemo::abi::elide_transport_socket_receive`].
#[unsafe(no_mangle)]
pub extern "C" fn elide_transport_socket_receive(workload: u64, driver: u64, socket: u64, buffer: u64) -> u64 {
  bemo::abi::elide_transport_socket_receive(workload, driver, socket, buffer)
}

/// Forward to [`bemo::abi::elide_transport_socket_receive_new`].
#[unsafe(no_mangle)]
pub extern "C" fn elide_transport_socket_receive_new(
  workload: u64,
  driver: u64,
  socket: u64,
  owner: u64,
  capacity: u64,
) -> u64 {
  bemo::abi::elide_transport_socket_receive_new(workload, driver, socket, owner, capacity)
}

/// Forward to [`bemo::abi::elide_transport_socket_receive_new_result`].
///
/// # Safety
/// The caller must satisfy the safety contract of [`bemo::abi::elide_transport_socket_receive_new_result`].
#[unsafe(no_mangle)]
pub unsafe extern "C" fn elide_transport_socket_receive_new_result(
  workload: u64,
  driver: u64,
  socket: u64,
  owner: u64,
  capacity: u64,
  output: *mut ReceiveResult,
) -> i32 {
  // SAFETY: the exported contract is identical to the Rust handle API.
  unsafe { bemo::abi::elide_transport_socket_receive_new_result(workload, driver, socket, owner, capacity, output) }
}

/// Forward to [`bemo::abi::elide_transport_socket_send`].
#[unsafe(no_mangle)]
pub extern "C" fn elide_transport_socket_send(
  workload: u64,
  driver: u64,
  socket: u64,
  buffer: u64,
  offset: u64,
  length: u64,
) -> u64 {
  bemo::abi::elide_transport_socket_send(workload, driver, socket, buffer, offset, length)
}

/// Forward to [`bemo::abi::elide_transport_socket_send_inline`].
///
/// # Safety
/// The caller must satisfy the safety contract of [`bemo::abi::elide_transport_socket_send_inline`].
#[unsafe(no_mangle)]
pub unsafe extern "C" fn elide_transport_socket_send_inline(
  workload: u64,
  driver: u64,
  socket: u64,
  source: *const u8,
  length: u64,
) -> i64 {
  // SAFETY: the exported contract is identical to the Rust handle API.
  unsafe { bemo::abi::elide_transport_socket_send_inline(workload, driver, socket, source, length) }
}

/// Forward to [`bemo::abi::elide_transport_socket_send_gathered`].
///
/// # Safety
/// The caller must satisfy the safety contract of [`bemo::abi::elide_transport_socket_send_gathered`].
#[unsafe(no_mangle)]
pub unsafe extern "C" fn elide_transport_socket_send_gathered(
  workload: u64,
  driver: u64,
  socket: u64,
  regions: *const u64,
  count: u32,
) -> u64 {
  // SAFETY: the exported contract is identical to the Rust handle API.
  unsafe { bemo::abi::elide_transport_socket_send_gathered(workload, driver, socket, regions, count) }
}

/// Forward to [`bemo::abi::elide_transport_socket_close`].
#[unsafe(no_mangle)]
pub extern "C" fn elide_transport_socket_close(driver: u64, socket: u64) -> i32 {
  bemo::abi::elide_transport_socket_close(driver, socket)
}

/// Forward to [`bemo::abi::elide_transport_socket_option`].
#[unsafe(no_mangle)]
pub extern "C" fn elide_transport_socket_option(driver: u64, socket: u64, option: u32, value: i32) -> i32 {
  bemo::abi::elide_transport_socket_option(driver, socket, option, value)
}

/// Forward to [`bemo::abi::elide_transport_socket_shutdown`].
#[unsafe(no_mangle)]
pub extern "C" fn elide_transport_socket_shutdown(driver: u64, socket: u64, direction: u32) -> i32 {
  bemo::abi::elide_transport_socket_shutdown(driver, socket, direction)
}

/// Forward to [`bemo::abi::elide_transport_driver_poll`].
///
/// # Safety
/// The caller must satisfy the safety contract of [`bemo::abi::elide_transport_driver_poll`].
#[unsafe(no_mangle)]
pub unsafe extern "C" fn elide_transport_driver_poll(driver: u64, timeout_ns: u64, batch: u64, maximum: u32) -> i32 {
  // SAFETY: the exported contract is identical to the Rust handle API.
  unsafe { bemo::abi::elide_transport_driver_poll(driver, timeout_ns, batch, maximum) }
}

/// Forward to [`bemo::abi::elide_transport_driver_poll_callback`].
///
/// # Safety
/// The caller must satisfy the safety contract of [`bemo::abi::elide_transport_driver_poll_callback`].
#[unsafe(no_mangle)]
pub unsafe extern "C" fn elide_transport_driver_poll_callback(
  workload: u64,
  driver: u64,
  timeout_ns: u64,
  maximum: u32,
  callback: Option<unsafe extern "C" fn(*mut c_void, *const NativeEvent) -> i32>,
  context: *mut c_void,
) -> i32 {
  // SAFETY: the exported contract is identical to the Rust handle API.
  unsafe { bemo::abi::elide_transport_driver_poll_callback(workload, driver, timeout_ns, maximum, callback, context) }
}

/// Forward to [`bemo::abi::elide_transport_driver_poll_batch_callback`].
///
/// # Safety
/// The caller must satisfy the safety contract of [`bemo::abi::elide_transport_driver_poll_batch_callback`].
#[unsafe(no_mangle)]
pub unsafe extern "C" fn elide_transport_driver_poll_batch_callback(
  workload: u64,
  driver: u64,
  timeout_ns: u64,
  maximum: u32,
  callback: Option<unsafe extern "C" fn(*mut c_void, *const NativeEvent, u32) -> i32>,
  context: *mut c_void,
) -> i32 {
  // SAFETY: the exported contract is identical to the Rust handle API.
  unsafe {
    bemo::abi::elide_transport_driver_poll_batch_callback(workload, driver, timeout_ns, maximum, callback, context)
  }
}

/// Forward to [`bemo::abi::elide_transport_tls_client`].
#[unsafe(no_mangle)]
pub extern "C" fn elide_transport_tls_client(workload: u64, roots: u64, alpn: u64) -> u64 {
  bemo::abi::elide_transport_tls_client(workload, roots, alpn)
}

/// Forward to [`bemo::abi::elide_transport_tls_server`].
#[unsafe(no_mangle)]
pub extern "C" fn elide_transport_tls_server(workload: u64, chain: u64, key: u64, alpn: u64) -> u64 {
  bemo::abi::elide_transport_tls_server(workload, chain, key, alpn)
}

/// Forward to [`bemo::abi::elide_transport_tls_context_release`].
#[unsafe(no_mangle)]
pub extern "C" fn elide_transport_tls_context_release(context: u64) -> i32 {
  bemo::abi::elide_transport_tls_context_release(context)
}

/// Forward to [`bemo::abi::elide_transport_tls_new`].
#[unsafe(no_mangle)]
pub extern "C" fn elide_transport_tls_new(workload: u64, context: u64, owner: u64, name: u64) -> u64 {
  bemo::abi::elide_transport_tls_new(workload, context, owner, name)
}

/// Forward to [`bemo::abi::elide_transport_tls_feed`].
#[unsafe(no_mangle)]
pub extern "C" fn elide_transport_tls_feed(session: u64, input: u64, length: u64) -> i32 {
  bemo::abi::elide_transport_tls_feed(session, input, length)
}

/// Forward to [`bemo::abi::elide_transport_tls_step`].
#[unsafe(no_mangle)]
pub extern "C" fn elide_transport_tls_step(
  session: u64,
  action: u32,
  plaintext: u64,
  offset: u64,
  length: u64,
  output: u64,
) -> i32 {
  bemo::abi::elide_transport_tls_step(session, action, plaintext, offset, length, output)
}

/// Forward to [`bemo::abi::elide_transport_tls_protocol`].
#[unsafe(no_mangle)]
pub extern "C" fn elide_transport_tls_protocol(session: u64, output: u64) -> i32 {
  bemo::abi::elide_transport_tls_protocol(session, output)
}

/// Forward to [`bemo::abi::elide_transport_tls_release`].
#[unsafe(no_mangle)]
pub extern "C" fn elide_transport_tls_release(session: u64) -> i32 {
  bemo::abi::elide_transport_tls_release(session)
}

/// Forward to [`bemo::abi::elide_transport_abi_version`].
#[unsafe(no_mangle)]
pub extern "C" fn elide_transport_abi_version() -> u32 {
  bemo::abi::elide_transport_abi_version()
}

/// Forward to [`bemo::abi::elide_transport_owner_new`].
#[unsafe(no_mangle)]
pub extern "C" fn elide_transport_owner_new(limit: u64) -> u64 {
  bemo::abi::elide_transport_owner_new(limit)
}

/// Forward to [`bemo::abi::elide_transport_owner_used`].
#[unsafe(no_mangle)]
pub extern "C" fn elide_transport_owner_used(owner: u64) -> u64 {
  bemo::abi::elide_transport_owner_used(owner)
}

/// Forward to [`bemo::abi::elide_transport_owner_release`].
#[unsafe(no_mangle)]
pub extern "C" fn elide_transport_owner_release(owner: u64) -> i32 {
  bemo::abi::elide_transport_owner_release(owner)
}

/// Forward to [`bemo::abi::elide_transport_workload_close`].
#[unsafe(no_mangle)]
pub extern "C" fn elide_transport_workload_close(workload: u64) -> i32 {
  bemo::abi::elide_transport_workload_close(workload)
}

/// Forward to [`bemo::abi::elide_transport_buffer_new`].
#[unsafe(no_mangle)]
pub extern "C" fn elide_transport_buffer_new(owner: u64, capacity: u64) -> u64 {
  bemo::abi::elide_transport_buffer_new(owner, capacity)
}

/// Forward to [`bemo::abi::elide_transport_buffer_view`].
///
/// # Safety
/// The caller must satisfy the safety contract of [`bemo::abi::elide_transport_buffer_view`].
#[unsafe(no_mangle)]
pub unsafe extern "C" fn elide_transport_buffer_view(handle: u64, output: *mut BufferView) -> i32 {
  // SAFETY: the exported contract is identical to the Rust handle API.
  unsafe { bemo::abi::elide_transport_buffer_view(handle, output) }
}

/// Forward to [`bemo::abi::elide_transport_buffer_freeze`].
///
/// # Safety
/// The caller must satisfy the safety contract of [`bemo::abi::elide_transport_buffer_freeze`].
#[unsafe(no_mangle)]
pub unsafe extern "C" fn elide_transport_buffer_freeze(handle: u64, length: u64) -> i32 {
  // SAFETY: the exported contract is identical to the Rust handle API.
  unsafe { bemo::abi::elide_transport_buffer_freeze(handle, length) }
}

/// Forward to [`bemo::abi::elide_transport_buffer_slice`].
#[unsafe(no_mangle)]
pub extern "C" fn elide_transport_buffer_slice(handle: u64, offset: u64, length: u64) -> u64 {
  bemo::abi::elide_transport_buffer_slice(handle, offset, length)
}

/// Forward to [`bemo::abi::elide_transport_buffer_release`].
#[unsafe(no_mangle)]
pub extern "C" fn elide_transport_buffer_release(handle: u64) -> i32 {
  bemo::abi::elide_transport_buffer_release(handle)
}

/// Forward to [`bemo::abi::elide_transport_driver_new`].
#[unsafe(no_mangle)]
pub extern "C" fn elide_transport_driver_new(workload: u64, backend: u32, limit: u32) -> u64 {
  bemo::abi::elide_transport_driver_new(workload, backend, limit)
}

/// Forward to [`bemo::abi::elide_transport_driver_backend`].
#[unsafe(no_mangle)]
pub extern "C" fn elide_transport_driver_backend(handle: u64) -> i32 {
  bemo::abi::elide_transport_driver_backend(handle)
}

/// Forward to [`bemo::abi::elide_transport_driver_fallback`].
#[unsafe(no_mangle)]
pub extern "C" fn elide_transport_driver_fallback(handle: u64, output: u64) -> i32 {
  bemo::abi::elide_transport_driver_fallback(handle, output)
}

/// Forward to [`bemo::abi::elide_transport_driver_wake`].
#[unsafe(no_mangle)]
pub extern "C" fn elide_transport_driver_wake(handle: u64) -> i32 {
  bemo::abi::elide_transport_driver_wake(handle)
}

/// Forward to [`bemo::abi::elide_transport_driver_release`].
#[unsafe(no_mangle)]
pub extern "C" fn elide_transport_driver_release(handle: u64) -> i32 {
  bemo::abi::elide_transport_driver_release(handle)
}
