[package]
name = "bemo-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[workspace]

[dependencies]
bemo = { path = "../crates/bemo", default-features = false, features = ["rust-allocator"] }
libfuzzer-sys = "=0.4.13"

[[bin]]
name = "http"
path = "fuzz_targets/http.rs"
test = false
doc = false
bench = false

[[bin]]
name = "buffers"
path = "fuzz_targets/buffers.rs"
test = false
doc = false
bench = false

[[bin]]
name = "abi"
path = "fuzz_targets/abi.rs"
test = false
doc = false
bench = false
