[package]
name = "bemo-ffi"
description = "Shared C ABI for Bemo FFM and Native Image bindings"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
links = "bemo"

[lib]
name = "bemo_ffi"
crate-type = ["rlib", "staticlib", "cdylib"]

[dependencies]
bemo = { workspace = true, default-features = false }

[features]
default = ["bundled-mimalloc"]
bundled-mimalloc = ["bemo/bundled-mimalloc"]
rust-allocator = ["bemo/rust-allocator"]

[lints]
workspace = true
