#!/usr/bin/env python3
"""Generate the thin C boundary from the Rust handle API; never duplicate transport logic."""
import argparse
from pathlib import Path
import re
import subprocess

ROOT = Path(__file__).resolve().parents[1]


def arguments(text):
  result, start, depth = [], 0, 0
  for index, char in enumerate(text):
    if char in "(<[":
      depth += 1
    elif char in ")>]" and not (char == ">" and text[index - 1] == "-"):
      depth -= 1
    elif char == "," and depth == 0:
      result.append(text[start:index].strip())
      start = index + 1
  if text[start:].strip():
    result.append(text[start:].strip())
  return result


def generate():
  output = ['''// @generated by tools/generate_exports.py; do not edit.
//! C exports preserving Elide transport ABI 3.
#![allow(clippy::too_many_arguments)]
use bemo::abi::{BufferView, NativeEvent, ReceiveResult};
use std::ffi::c_void;
''']
  names = set()
  base = ROOT / "crates/bemo/src"
  for path in sorted([base / "abi.rs", *(base / "abi").rglob("*.rs")]):
    source = path.read_text()
    for match in re.finditer(r'^pub (unsafe )?fn (elide_transport_\w+)\(', source, re.M):
      unsafe, name = match.groups()
      depth, end = 1, match.end()
      while depth:
        if source[end] == "(": depth += 1
        elif source[end] == ")": depth -= 1
        end += 1
      params = source[match.end():end - 1]
      returns = source[end:source.index("{", end)].strip()
      args = ", ".join(arg.split(":", 1)[0].strip() for arg in arguments(params))
      module = "bemo::abi::engine" if path.name == "engine.rs" else "bemo::abi"
      target = f"{module}::{name}"
      names.add(name)
      output.append(f"/// Forward to [`{target}`].\n")
      if unsafe:
        output.append(f"///\n/// # Safety\n/// The caller must satisfy the safety contract of [`{target}`].\n")
      output.append(f'#[unsafe(no_mangle)]\npub {unsafe or ""}extern "C" fn {name}({params}) {returns} {{\n')
      if unsafe:
        output.append(f"  // SAFETY: the exported contract is identical to the Rust handle API.\n  unsafe {{ {target}({args}) }}\n")
      else:
        output.append(f"  {target}({args})\n")
      output.append("}\n\n")
  header = (ROOT / "include/elide_transport.h").read_text()
  declarations = set(re.findall(r'^\w+[\w\s*]*\b(elide_transport_\w+)\(', header, re.M))
  if declarations != names:
    raise RuntimeError(f"Header/export mismatch: {sorted(declarations ^ names)}")
  result = subprocess.run(["rustfmt", "--edition", "2024", "--emit", "stdout"],
                          input="".join(output), text=True, capture_output=True, check=True, cwd=ROOT)
  return result.stdout


if __name__ == "__main__":
  parser = argparse.ArgumentParser(description=__doc__)
  parser.add_argument("--check", action="store_true")
  options = parser.parse_args()
  output = ROOT / "crates/bemo-ffi/src/transport.rs"
  expected = generate()
  if options.check:
    if output.read_text() != expected:
      raise SystemExit("C exports are stale; run python3 tools/generate_exports.py")
  else:
    output.write_text(expected)
