[package]
name = "dokar-ffi"
description = "Shared C ABI for Dokar FFM and Native Image bindings"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
name = "dokar_ffi"
crate-type = ["rlib", "staticlib", "cdylib"]

[dependencies]
dokar.workspace = true

[lints]
workspace = true
