name: Push
on:
  push:
    branches: [main]
  schedule:
    - cron: "17 5 * * *"
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
  actions: read
  id-token: write
  attestations: write
  artifact-metadata: write
concurrency:
  group: push-${{ github.ref }}
  cancel-in-progress: false
jobs:
  verify:
    permissions:
      contents: read
      actions: read
      id-token: write
      attestations: write
      artifact-metadata: write
    uses: ./.github/workflows/on.verify.yml
  release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [verify]
    uses: ./.github/workflows/job.release.yml
    permissions:
      contents: write
      pull-requests: write
      actions: read
      id-token: write
  packages:
    needs: [verify, release]
    uses: ./.github/workflows/job.packages.yml
    permissions:
      contents: read
      actions: read
      packages: write
  central:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && needs.release.outputs.version != ''
    needs: [verify, release]
    uses: ./.github/workflows/on.central.yml
    with:
      version: ${{ needs.release.outputs.version }}
    permissions:
      contents: read
