name: PR
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
permissions:
  contents: read
concurrency:
  group: pr-${{ github.event.number }}
  cancel-in-progress: true
jobs:
  verify:
    uses: ./.github/workflows/on.verify.yml
