<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>dev.elide.bemo.examples</groupId>
  <artifactId>quickstart</artifactId>
  <version>1.0.0</version>
  <properties>
    <maven.compiler.release>22</maven.compiler.release>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <bemo.version>0.3.0</bemo.version>
    <bemo.classifier>linux-x86_64-gnu</bemo.classifier>
  </properties>
  <dependencies>
    <dependency>
      <groupId>dev.elide.bemo</groupId>
      <artifactId>bemo-netty</artifactId>
      <version>${bemo.version}</version>
    </dependency>
    <dependency>
      <groupId>dev.elide.bemo</groupId>
      <artifactId>bemo-ffm</artifactId>
      <version>${bemo.version}</version>
    </dependency>
    <dependency>
      <groupId>dev.elide.bemo</groupId>
      <artifactId>bemo-ffm</artifactId>
      <version>${bemo.version}</version>
      <classifier>${bemo.classifier}</classifier>
      <scope>runtime</scope>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.14.1</version>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <version>3.9.0</version>
      </plugin>
    </plugins>
  </build>
</project>
